import React from 'react';
import { Button } from '../components/Button';
import { 
  FileText, 
  Download, 
  Filter, 
  Calendar, 
  ArrowRight,
  TrendingUp,
  AlertTriangle,
  Scale,
  Calculator
} from 'lucide-react';
import { cn } from '../lib/utils';

const reportTypes = [
  { id: 'stock', name: 'Stock Report', desc: 'Detailed list of all items with current quantities and values.', icon: FileText },
  { id: 'valuation', name: 'Valuation Report', desc: 'Financial summary of inventory value using selected methods.', icon: Calculator },
  { id: 'variance', name: 'Variance Report', desc: 'Comparison between system stock and physical verification.', icon: Scale },
  { id: 'ageing', name: 'Ageing Report', desc: 'Analysis of stock duration to identify slow-moving items.', icon: TrendingUp },
  { id: 'low-stock', name: 'Low Stock Report', desc: 'Items that have fallen below their reorder levels.', icon: AlertTriangle },
];

export const Reports: React.FC = () => {
  return (
    <div className="flex flex-col gap-8">
      {/* Report Selection Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        {reportTypes.map((report) => (
          <div key={report.id} className="bg-white p-6 rounded-xl border border-border shadow-sm hover:border-primary/30 transition-all flex flex-col gap-4 group">
            <div className="flex items-start justify-between">
              <div className="w-12 h-12 bg-primary/5 rounded-lg flex items-center justify-center text-primary group-hover:bg-primary group-hover:text-white transition-colors">
                <report.icon size={24} />
              </div>
              <Button variant="ghost" size="sm" className="p-1.5 opacity-0 group-hover:opacity-100 transition-opacity">
                <Download size={18} className="text-gray-400" />
              </Button>
            </div>
            <div className="flex flex-col gap-2">
              <h4 className="font-bold text-primary">{report.name}</h4>
              <p className="text-sm text-gray-500 leading-relaxed">{report.desc}</p>
            </div>
            <div className="mt-2 pt-4 border-t border-border flex items-center justify-between">
              <div className="flex items-center gap-2 text-xs text-gray-400 font-medium">
                <Calendar size={14} />
                Last generated: 2 days ago
              </div>
              <Button variant="ghost" size="sm" className="text-xs font-bold text-primary gap-1">
                Generate
                <ArrowRight size={14} />
              </Button>
            </div>
          </div>
        ))}
      </div>

      {/* Recent Reports Table */}
      <div className="bg-white rounded-lg border border-border shadow-sm overflow-hidden">
        <div className="p-6 border-b border-border flex items-center justify-between">
          <h3 className="font-bold text-primary">Recently Generated Reports</h3>
          <div className="flex items-center gap-3">
            <Button variant="outline" size="sm" className="gap-2">
              <Filter size={16} />
              Filter
            </Button>
          </div>
        </div>
        <div className="overflow-x-auto">
          <table className="w-full text-left border-collapse">
            <thead>
              <tr className="bg-gray-50 border-b border-border">
                <th className="px-6 py-4 text-xs font-bold text-gray-500 uppercase tracking-wider">Report Name</th>
                <th className="px-6 py-4 text-xs font-bold text-gray-500 uppercase tracking-wider">Type</th>
                <th className="px-6 py-4 text-xs font-bold text-gray-500 uppercase tracking-wider">Generated By</th>
                <th className="px-6 py-4 text-xs font-bold text-gray-500 uppercase tracking-wider">Date & Time</th>
                <th className="px-6 py-4 text-xs font-bold text-gray-500 uppercase tracking-wider">Format</th>
                <th className="px-6 py-4 text-xs font-bold text-gray-500 uppercase tracking-wider text-right">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-border">
              {[
                { name: 'Monthly Valuation - March 2026', type: 'Valuation', user: 'Pradnya C.', date: '2026-04-01 10:30 AM', format: 'PDF' },
                { name: 'Warehouse A Physical Audit', type: 'Variance', user: 'Rajesh K.', date: '2026-03-28 04:15 PM', format: 'Excel' },
                { name: 'Year-end Stock Summary', type: 'Stock', user: 'Pradnya C.', date: '2026-03-25 09:00 AM', format: 'PDF' },
                { name: 'Slow Moving Items Q1', type: 'Ageing', user: 'Amit S.', date: '2026-03-20 11:45 AM', format: 'Excel' },
              ].map((row, i) => (
                <tr key={i} className="hover:bg-gray-50 transition-colors">
                  <td className="px-6 py-4 text-sm font-bold text-primary">{row.name}</td>
                  <td className="px-6 py-4 text-sm text-gray-600">{row.type}</td>
                  <td className="px-6 py-4 text-sm text-gray-600">{row.user}</td>
                  <td className="px-6 py-4 text-sm text-gray-500">{row.date}</td>
                  <td className="px-6 py-4 text-sm">
                    <span className={cn(
                      'px-2 py-1 rounded text-xs font-bold',
                      row.format === 'PDF' ? 'bg-red-50 text-red-700' : 'bg-green-50 text-green-700'
                    )}>
                      {row.format}
                    </span>
                  </td>
                  <td className="px-6 py-4 text-sm text-right">
                    <div className="flex items-center justify-end gap-2">
                      <Button variant="ghost" size="sm" className="p-1.5">
                        <Download size={18} className="text-gray-400" />
                      </Button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
};
